export const UPDATE_TRANSCRIPT = "UPDATE_TRANSCRIPT"
export const CLEAR_TRANSCRIPT = "CLEAR_TRANSCRIPT"
export const START_LISTENING = "START_LISTENING"
export const STOP_LISTENING  = "STOP_LISTENING"